export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAIL = "FETCH_JOBS_FAIL";

export const SET_APPLICATION_DATA_REQUEST = "SET_APPLICATION_DATA_REQUEST";
export const SET_APPLICATION_DATA_SUCCESS = "SET_APPLICATION_DATA_SUCCESS";
export const SET_APPLICATION_DATA_FAIL = "SET_APPLICATION_DATA_FAIL";

export const TOGGLE_SUCCESS_PAGE_REQUEST = "TOGGLE_SUCCESS_PAGE_REQUEST";
export const TOGGLE_SUCCESS_PAGE_SUCCESS = "TOGGLE_SUCCESS_PAGE_SUCCESS";
export const TOGGLE_SUCCESS_PAGE_FAIL = "TOGGLE_SUCCESS_PAGE_REQUEST_FAIL";
